# storageClassName not set. The default storage
# class in classroom will be matched. Since the
# default storage class supports dynamic provisioning
# this pvc will be bound to the dynamically created pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
